apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: pulse-notify
  labels:
    app: delivery-service
spec:
  type: ClusterIP
  selector:
    app: delivery-service
  ports:
    - name: http
      port: 8082
      targetPort: http
